FROM wordpress:latest

WORKDIR /var/www/html

COPY . .

ENV WORDPRESS_DB_HOST=wordpress11.cjhrqy0ejiqm.us-east-1.rds.amazonaws.com \
    WORDPRESS_DB_USER=wordpress11 \
    WORDPRESS_DB_PASSWORD=wordpress11 \
    WORDPRESS_DB_NAME=wordpress11

EXPOSE 80

CMD ["apache2-foreground"]
